<a href="https://colab.research.google.com/github/akash-barman007/IDRA_DSAI_day11/blob/main/Day11_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning: Company Employee Dataset

In [1]:
import pandas as pd

# Load the dataset
file_path = '/content/Day11_Messy_Company_Employee_Dataset.csv'
df = pd.read_csv(file_path)

# Initial Inspection
print("Dataset Shape:", df.shape)
print("\nColumn Info:")
display(df.info())
print("\nFirst 5 rows:")
display(df.head())

Dataset Shape: (157, 12)

Column Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

None

First 5 rows:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [2]:
# 1. Identify and Quantify Missing Values
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values > 0])

# 2. Check for Duplicate Records
duplicates_count = df.duplicated().sum()
print(f"\nTotal duplicate records: {duplicates_count}")

Missing values per column:
Department           5
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

Total duplicate records: 7

In [3]:
# 3. Data Cleaning

# Remove duplicates
df_cleaned = df.drop_duplicates().copy()

# Example Cleaning Strategy (Adjust based on specific column needs observed in info):
# - For numeric columns with few missing values, use median imputation
# - For categorical columns, use mode or 'Unknown'
# - For unique identifiers, drop rows with missing values

# Filling missing numeric values (if any) with median
numeric_cols = df_cleaned.select_dtypes(include=['number']).columns
df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())

# Filling categorical values with mode or placeholder
object_cols = df_cleaned.select_dtypes(include=['object']).columns
for col in object_cols:
    df_cleaned[col] = df_cleaned[col].fillna(df_cleaned[col].mode()[0] if not df_cleaned[col].mode().empty else 'Unknown')

print("Cleaning complete. Current missing values count:", df_cleaned.isnull().sum().sum())

Cleaning complete. Current missing values count: 0

In [4]:
# 4. Verification and Export
print("Final Dataset Shape:", df_cleaned.shape)

# Export to CSV
output_path = '/content/Cleaned_Company_Employee_Dataset.csv'
df_cleaned.to_csv(output_path, index=False)
print(f"Cleaned dataset saved to: {output_path}")

display(df_cleaned.head())

Final Dataset Shape: (150, 12)
Cleaned dataset saved to: /content/Cleaned_Company_Employee_Dataset.csv

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid